---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: cf-sb-resource
  path: gopath/src/github.com/idahobean/cf-sb-resource
- name: cf-cli

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/idahobean/cf-sb-resource/scripts/ci
